### ISSUE TITLE
你好，问下 在哪里可以开启sql语句的打印？非常感谢

### ISSUE THREAD

**Issue by tom055** [jetlinks/jetlinks-community#243]
你好，问下 在哪里可以开启sql语句的打印？非常感谢

**Comment by zhou-hao** [comment]
设置日志级别:
```yml
logging:
   level:
     org.hswebframework.ezorm: debug
```
