### ISSUE TITLE
Exceeded limit on max bytes to buffer 262144

### ISSUE THREAD

**Issue by jyy1990** [jetlinks/jetlinks-community#519]
用docker部署到服务器后，仪表盘的查询图表如果日期范围选大，接口就报错：：Exceeded limit on max bytes to buffer 262144。
而我在本地开发环境没有这个问题，用jar包的方式部署到服务器也没有这个问题。
网上搜了一下加什么spring.codec.max-in-memory-size的配置并没有什么用

**Comment by zhou-hao** [comment]
修改这个配置试试

```yml
spring:
    elasticsearch:
      webclient:
          max-in-memory-size: 100MB
```
